spring:
  application:
    name: server-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.4:3306/seata?characterEncoding=utf-8&useSSL=false
  seata:
    config:
      type: nacos
      nacos:
        server-addr: 192.168.1.4:8848
        group: "SEATA_GROUP"
        namespace: ""
        username: "nacos"
        password: "nacos"
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848